#!/usr/bin/env bash
# Copyright (C) 2018  Luke Shumaker
# Copyright (C) 2018  Datawire
# SPDX-License-Identifier: AGPL-3.0-or-later

set -euE
{
	cat <<-'EOT' > ./etc/systemd/system/testbench-run.target
		[Unit]
		Description=testbench-run target
		Requires=multi-user.target
		After=multi-user.target
		Conflicts=rescue.target
		AllowIsolate=yes
		EOT
	ln -sfT -- testbench-run.target ./etc/systemd/system/default.target

	install /dev/stdin ./etc/testbench-run <<-EOT
		#!/bin/sh
		$(printf '%q ' "$@")
		EOT

	cat <<-'EOT' > ./etc/systemd/system/testbench-run.service
		[Unit]
		Description=testbench-run service
		Wants=network-online.target
		After=network-online.target
		ConditionFileIsExecutable=/etc/testbench-run

		[Service]
		User=testbench
		WorkingDirectory=/home/testbench
		ExecStart=/etc/testbench-run
		StandardOutput=file:/var/log/testbench-run.tap
		ExecStopPost=+/bin/sh -c 'rm -f /etc/testbench-run; systemctl poweroff --no-block'

		[Install]
		WantedBy=testbench-run.target
		EOT
	systemctl --root="$PWD" enable testbench-run.service
}
